version: '3.1'
services:
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
  message_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python messageConsumer.py'